# Generated by Django 4.0.6 on 2022-09-02 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='img.jpeg', upload_to='src/static/imagination')),
                ('tel', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lat', models.DecimalField(decimal_places=14, default=53.90253146975031, max_digits=100, verbose_name='lat')),
                ('lng', models.DecimalField(decimal_places=14, default=27.561436808736307, max_digits=100, verbose_name='lng')),
                ('gla', models.DecimalField(decimal_places=2, default=5000.0, max_digits=20, verbose_name='gla')),
                ('office_class', models.CharField(choices=[('A', 'A'), ('B1', 'B1'), ('B2', 'B2')], default='B1', max_length=40)),
                ('rent', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='rent')),
                ('image', models.ImageField(default='img.jpeg', upload_to='src/static/imagination')),
                ('type', models.CharField(choices=[('Existing', 'Existing'), ('Pipeline', 'Pipeline'), ('Completed in 2022', 'Completed in 2022')], default='B1', max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officesrates.broker')),
            ],
        ),
    ]
